GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new

Content-Type: application/json
{
    "text": "im literally testing"
}

###

DELETE http://localhost:3001/todo/delete/61bd561ae9ce6acc4d69f911

###

PUT http://localhost:3001/todo/complete/61bd561ae9ce6acc4d69f911